hydra: 
  output_subdir: null 
  job: 
    chdir: false
  run: 
    dir: .

# Main configuration file with defaults
defaults:
  - model: default
  - dataset: default 
  - training: default
  - accelerate: single
  - _self_ 


# Model shared params
dropout: 0.1
d_latent: 768
d_latent_debug: 256
pretrained_lm: Qwen/Qwen2.5-Coder-0.5B-Instruct 
max_action_len: 1024
max_precept_len: 1024
n_self_attn_heads: 8
n_cross_attn_heads: 8






    
